### ISSUE TITLE
Addresses sent to Discovery Inputs need to be labelled

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#10]
To view the Address book and see all of the wallet addresses, open the wallet and:

1. Click the menu button (top-left)
2. press ADDRESS BOOK
3. Swipe left to see "Your addresses".

When an address is sent to /api/v1/discoveryInputs, give the address this exact label: <code>WallofCoins.com</code>

When the user captures a hold (creating an order) for that discovery input item, grab the order ID from response JSON and change the addresses label to be exactly this:

<code>WallofCoins.com - Order {{ ID HERE }}</code>

For example:

<code>WallofCoins.com - Order 103789</code>

Requirements: addresses we use CANNOT have the label "(unlabeled)".

![screenshot_20180105-033010](https://user-images.githubusercontent.com/368863/34601195-df1cf09c-f1c8-11e7-8b33-5e8bfc33b410.png)

**Comment by jaydeep82** [comment]
@rgenito This issue has been fixed.

**Comment by rgenito** [comment]
Hi @jaydeep82 ,

This feature is incomplete. Below is the process I did to reach this screen shot, followed by the screen shot with annotated points.

To get to the screen shot, perform the following with the MAINNET app (i'm sure this problem still exists with TESTNET)...

1. Delete the current installation of the app.
2. Freshly install and Open the app.
3. Press the Menu button (top-left)
4. Press "Address book"
5. Swipe right to access "Your addresses"
6. Witness the current address that is listed. This is exactly as expected.
7. Press the Back button
8. Press "load your new Dash Wallet!"
9. Complete the Buy Wizard process to create a new order.

![address-book](https://user-images.githubusercontent.com/368863/35255322-78e2afd6-ffbc-11e7-8ba0-70ef0d988c40.jpg)

C: this is the address that I first looked at. Our code is intentionally reserving this address for the end user, and this is *NOT* the address that was sent to Wall of Coins, and it will never be the address sent to Wall of Coins. The Label must correctly state "(unlabeled)".

B: This *is* the address that was sent to the discovery input, and it needs to have a label EXACTLY AS SPECIFIED. For this instance of my QA test, the label should have been, "WallofCoins.com -
 Order 115566". However, you are incorrectly formatting the label as "WallofCoins.com Order {{ID}}" and you are missing the " - ". Fix this.

A: This is a new address that was generated by the Dash Wallet for the end user. I am expecting it to have the label "(unlabeled)" since no order was created with that address.

Jaydeep, please follow our specs exactly to save us project time. If you have any questions, this thread is the place to ask!

**Comment by jaydeep82** [comment]
@rgenito this issue has been fixed.

**Comment by rgenito** [comment]
Good job @jaydeep82 !
