### ISSUE TITLE
Buying Instructions include blank Account # when PayFields is activated.

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#26]
Hi Jaydeep, 

There are 2 tasks for this:
- [x] update the WallofCoins-README to include information about rendering the Payment Destinations' (or banks') "Account Name" and "Account Number" **OR** the Destination's "payfields".
- [x] Order from my developer instance and order from Money Gram. You will see that there is no "accountNumber" (it is JSON for the payment fields). When this is the case, do not render "Account #: -" on the Buying Instructions. In this case, you will only render the fields present in the Payment Fields.

![screenshot_20180129-103642](https://user-images.githubusercontent.com/368863/35518952-f0a68000-04e0-11e8-8ed1-5ece82078e92.jpg)

**Comment by jaydeep82** [comment]
@rgenito this point has been fixed.

**Comment by rgenito** [comment]
Hi @jaydeep82 i noticed another problem with this that i did not notice previously. However, this will go into our Q1 2018 updates.

- [ ] The name of the payment destination (which is "Money Gram" in this case) is COMPLETELY MISSING from the Buying Instructions! Look at the annotated screen shot above.
- [ ] QUESTION: Since Moneygram does not return (in the JSON) a nearest location, we need to supply a web link for them to check nearby locations. Use the label/href as you render on the Offers screen. For example...

* The left side will contain the Payment Destination's branding icon (you are already doing this)
* The right side will contain: {{Payment Destination Name}} \n Subject to local availability. \n [Check Locations Nearby]({{ URL to the payment destination's locations website }})

For example, the right side will have:


Money Gram
Subject to local availability.
[Check Locations Nearby](https://secure.moneygram.com/locations?gclid=Cj0KCQiAzMDTBRDDARIsABX4AWzE2uI56yoTiGLJ59afZsLfg6vvhJb_c7mEk5Dancb3XTcN0TmnFucaAtyOEALw_wcB&gclsrc=aw.ds&dclid=CPr-pNTRgNkCFdEahwodo_gDDw)

**Comment by jaydeep82** [comment]
@rgenito both issues have been fixed.
