### ISSUE TITLE
Buy Wizard: Bank Icons disappear on 2nd discovery input call

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#50]
Now that I can see the banking icons, I am experiencing this issue with the MainNet build. Here's how you recreate the issue:

1. go to the Buy Wizard
2. search for $60 to spend on Dash
3. When you see the OFFERS page, press the BACK (<-) icon to go back to the discovery input amount.
4. Press "NEXT" to re-do the search for $60.
5. Notice that the offers page now is either 1) missing the logos, or 2) the logos are much smaller.

![screenshot_20180220-233923](https://user-images.githubusercontent.com/368863/36463472-30f998d6-1698-11e8-89cf-5ef2fa501989.png)

**Comment by jaydeep82** [comment]
@rgenito this bug has been fixed.

**Comment by rgenito** [comment]
@jaydeep82 going forward, YOU ABSOLUTELY MUST reference your commit that has these fixes. Each commit must reference the ticket number.

**Comment by rgenito** [comment]
@jaydeep82 looks good, but how about you save the banking icons/logos locally ... so that you will use those icons/logos locally? You can always check the API's icons/logos to see if they have changed before downloading. If they change, we will change the name of the URL for the download :) (we should probably provide a file hash...)

**Comment by jaydeep82** [comment]
@rgenito code has used glider library which handle caching and smooth scrolling. It will automatically handle if the logo/icon file change.
